### ISSUE TITLE
The applet AID isn't correct for NDEF use anymore

### ISSUE THREAD

**Issue by benbenbenbenbenben** [OpenJavaCard/openjavacard-ndef#10]
Hi,

A colleague and I have noticed that the AID in the prebuilt cap files doesn't correspond to the correct AID for NDEF and so the applets are behaving as tags correctly at the moment.

**Comment by yp25** [comment]
it seems now the latest prebuilt cap files has
Package ID : D276000177100211010001  and
Application ID : D27600017710021101000101 

l try to find the other prebuilt applet it seems the last working applet has package ID D276000085  and AID D2760000850101 
`https://github.com/OpenJavaCard/openjavacard-ndef/commit/3aa1672bdc5a28088387853dc219894994127400`

**Comment by promovicz** [comment]
The new AID is deliberate. You need to set the correct AID yourself when installing the applet. This is because I have derived 'proper' AIDs from our project namespace. Did not have time to update the guides yet.

**Comment by promovicz** [comment]
For further details on the meaning of the various AID types check https://openjavacard.org/devguide/naming.html#aid-naming.

What gp.jar calls "Application AID" is actually a module AID. This then gets used as a default for the applet AID. But you can - and should - specify that yourself. The correct AID for NDEF Type 4 tags is D2760000850101.

**Comment by benbenbenbenbenben** [comment]
If your project has diverged from NDEF then shouldn't it be a fork away from this, and this project be kept as D2760000850101? After all this project has NDEF in the name.

**Comment by promovicz** [comment]
It has not diverged. It is just the tools defaulting to an AID that may or may not be the right one.

The reason for using an OJC AID is to prevent collisions in certain cases where multiple variants are preinstalled. I intend to always use 'proper' AIDs.

This project is still compliant to the spec, which says nothing about the module AID - just the applet AID. Documentation needs fixing.

**Comment by promovicz** [comment]
I have now fixed the usage instructions to specify the right applet AID.

As the commit states it is not really an option to "fix" the module AID in the CAP file since that will break other scenarios.
