### ISSUE TITLE
Use object deletion support for memory optimization

### ISSUE THREAD

**Issue by promovicz** [OpenJavaCard/openjavacard-ndef#2]
The applet should use object deletion when available to shrink the data array.

It should do so both for install-time configuration and when written by command.

**Comment by martinpaljak** [comment]
Object deletion, meaning... ?

**Comment by promovicz** [comment]
Decided not to do this as it just complicates things.

@martinpaljak Object deletion in this context means garbage collection, ie JCSystem.requestObjectDeletion().
