### ISSUE TITLE
Not work successfully

### ISSUE THREAD

**Issue by shimizus3106** [OpenJavaCard/openjavacard-ndef#3]
Hello, Developer.

I'm Shige in Japan user.
Thanks to your good javacard applet, its useful to me.

Please let me ask how to use javacard-ndef applet.

I believe that I can install successfully.
I installed with refering to

> >    java -jar gp.jar \
> >        -params 100BD101075402656E54657374 \
> >        -install javacard-ndef.cap

But, it doesnt work well.
  APDU Command with GP tool below:
   Success : 9000
   A>> T=0 (4+0007) 00A40400 07 D2760000850101
   A<< (0000+2) (41ms) 9000

  But, next is not success
  A>> T=0 (4+0002) 00A4000C 02 E103
  A<< (0000+2) (26ms) 6A86

Could you let me know how to use or example to call APDU ?  

Best Regards,
Shige

**Comment by promovicz** [comment]
Sorry for never getting back to you.

I think your problem occurs because the applet did not support T=0 at that point. This might work now, although I did not test it.

You will need to update your install params to use the new standards-compliant tags.

**Comment by promovicz** [comment]
Issue obsolete.
