### ISSUE TITLE
Wrong NDEF file length when creating CC file

### ISSUE THREAD

**Issue by cabidop** [OpenJavaCard/openjavacard-ndef#8]
After the installation of the `tiny` applet in a JCOP 3 EMV, the card is not recognized as a NFC tag. This happens due to the _Maximum NDEF file size_ field in the File Control TLV being set to the NDEF message size instead of to the NDEF file size.

The fix would be to use `(short)(dataSize + 2)` instead of `dataSize` when initializing the Capability Container in `makeCaps`.

**Comment by promovicz** [comment]
This has been fixed by the commit in July.
