### ISSUE TITLE
PN532 failing with Unknown TLV 67

### ISSUE THREAD

**Issue by systemx-xx** [OpenJavaCard/openjavacard-ndef#9]
Update: Fails on windows with GoToTags and ACR122u.

I cant seem to get to the PN532 and Arduino to read the tag, when I use ACR122U it works fine, however the Arduino can read a regular mifare card with the same NDEF tag fine. 

Loaded javacard-ndef-full-plain.cap onto J3A040
Created text ndef
Write ndef onto mifare and java card.

Reading Mifare and Java card with ACR122U works.
Reading Mifare and Java card with iPhone Xs works.
Reading Mifare with Arduino and PN532 works.
Reading Mifare with GoToTags Windows App with ACR122U works.

Reading Java card with Arduino and PN532 throws error, Unknown TLV 67.
Reading Java card with GoToTags Windows App with ACR122U does not work, Throws NFC tag's type is not supported.

**Comment by martinpaljak** [comment]
Couldn't this be a bug report to the Arduino software instead?

**Comment by systemx-xx** [comment]
> Couldn't this be a bug report to the Arduino software instead?

I have been able to get the Java card to fail under windows using the GotoTags Windows App with the ACR122U, this doesn't appear to be specific to the Arduino. The Mifare card works fine. I will update my initial issue.

**Comment by promovicz** [comment]
This looks like you are having issues with your clients, not the NDEF applet.

The Arduino library probably does not support the type of content you have written. Can you point out which library you are using so I can follow up on this? You might also create a ticket with them yourself. I am willing to support an effort to debug this.

The GoToTags application seems to be incompatible with the NFC applet. The applet implements a bare-minimum but fully compliant NDEF feature set. This application likely requires something that the applet does not implement. If you figure out what that is then I might be able to offer advice.

**Comment by promovicz** [comment]
This issue is closed with regards to openjavacard-ndef.

Please create a new issue or contact me personally if you wish me to follow up on your library problems.
